# Generated by Django 5.2.5 on 2025-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_slug_alter_ad_author_alter_ad_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
