# Generated by Django 5.2.5 on 2025-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_tag_alter_ad_slug_ad_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
