# Generated by Django 5.2.5 on 2025-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_ad_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
