# Generated by Django 5.2.5 on 2025-09-29 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ad_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
